### ISSUE TITLE
Build break?

### ISSUE THREAD

**Issue by huahang** [sustrik/libdill#149]
I get the following error when I try to compile libdill 2.6 or the master branch. Help!

    Makefile:1290: recipe for target 'tutorial/basics/step1' failed
    make[1]: *** [tutorial/basics/step1] Error 1
    ./.libs/libdill.so: undefined reference to `BIO_set_data'
    ./.libs/libdill.so: undefined reference to `BIO_get_new_index'
    ./.libs/libdill.so: undefined reference to `BIO_set_init'
    ./.libs/libdill.so: undefined reference to `BIO_meth_free'
    ./.libs/libdill.so: undefined reference to `BIO_meth_set_destroy'
    ./.libs/libdill.so: undefined reference to `BIO_meth_set_write'
    ./.libs/libdill.so: undefined reference to `BIO_meth_set_read'
    ./.libs/libdill.so: undefined reference to `BIO_get_data'
    ./.libs/libdill.so: undefined reference to `BIO_meth_new'
    ./.libs/libdill.so: undefined reference to `BIO_meth_set_create'
    ./.libs/libdill.so: undefined reference to `BIO_meth_set_ctrl'
    collect2: error: ld returned 1 exit status

**Comment by sustrik** [comment]
What version of opens are you using?

**Comment by huahang** [comment]
It is openssl 1.0.2g. It is the default version in ubuntu 16.04 LTS.

**Comment by sustrik** [comment]
--enable-tls: Build TLS protocol. To be able to build with this option you need OpenSSL 1.1.0. or later installed on your machine.

See here: http://libdill.org/build_options.html

**Comment by Gymmasssorla** [comment]
Also, If you have already installed OpenSSL v1.1.0 on Ubuntu but the error still exists, try re-installing your OpenSSL like this (for new guys):

```bash
$ sudo apt-get remove openssl
$ sudo apt-get install openssl

$ sudo apt-get remove libssl-dev
$ sudo apt-get install libssl-dev
```
