### PR TITLE
fix --disable-sockets

### PR DESCRIPTION
**Pull request by jimdigriz**
Similar to #120, looks like `--disable-sockets` is broken since 7e663dd467.
```
alex@aineko:~/src/libdill$ ./configure --enable-debug --disable-shared --disable-sockets --disable-tls
alex@aineko:~/src/libdill$ make V=1
[snipped]
gcc -DPACKAGE_NAME=\"libdill\" -DPACKAGE_TARNAME=\"libdill\" -DPACKAGE_VERSION=\"Unknown\" -DPACKAGE_STRING=\"libdill\ Unknown\" -DPACKAGE_BUGREPORT=\"sustrik@250bpm.com\" -DPACKAGE_URL=\"http://libdill.org/\" -DPACKAGE=\"libdill\" -DVERSION=\"Unknown\" -DDILL_THREADS=1 -DDILL_PTHREAD=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_MPROTECT=1 -DHAVE_LIBRT=1 -DHAVE_CLOCK_GETTIME=1 -DHAVE_EPOLL_CREATE=1 -DHAVE_EPOLL=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I.     -g -O2 -g -O0 -MT perf/go.o -MD -MP -MF $depbase.Tpo -c -o perf/go.o perf/go.c &&\
mv -f $depbase.Tpo $depbase.Po
/bin/bash ./libtool  --tag=CC   --mode=link gcc  -g -O2 -g -O0   -o perf/go perf/go.o libdill.la -lrt 
libtool: link: gcc -g -O2 -g -O0 -o perf/go perf/go.o  ./.libs/libdill.a -lpthread -lrt -pthread
./.libs/libdill.a(libdill_la-ctx.o): In function `dill_ctx_init_':
/home/alex/src/objmap/libdill/ctx.c:39: undefined reference to `dill_ctx_fd_init'
./.libs/libdill.a(libdill_la-ctx.o): In function `dill_ctx_term_':
/home/alex/src/objmap/libdill/ctx.c:47: undefined reference to `dill_ctx_fd_term'
collect2: error: ld returned 1 exit status
Makefile:1208: recipe for target 'perf/go' failed
make[1]: *** [perf/go] Error 1
make[1]: Leaving directory '/home/alex/src/objmap/libdill'
Makefile:1926: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

Compile tested, new to `libdill` so about to find out what this breaks :)

### CODE REVIEW

**Comment by jimdigriz** [comment]
Eugh, I'm a fool, should be using `DILL_DISABLE_SOCKETS`
