### ISSUE TITLE
Fails on macOS with gcc-4.2: `error: redefinition of typedef 'ct_assert___COUNTER__'`

### ISSUE THREAD

**Issue by barracuda156** [sustrik/libdill#231]
```
  CC       libdill_la-ipaddr.lo
ipc.c:352: error: redefinition of typedef 'ct_assert___COUNTER__'
ipc.c:67: error: previous declaration of 'ct_assert___COUNTER__' was here
make[1]: *** [libdill_la-ipc.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
ipaddr.c:52: error: redefinition of typedef 'ct_assert___COUNTER__'
ipaddr.c:51: error: previous declaration of 'ct_assert___COUNTER__' was here
make[1]: *** [libdill_la-ipaddr.lo] Error 1
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_libdill/libdill/work/libdill-2.14'
make: *** [all-recursive] Error 1
```
P. S. As noted in a ticket below, it also fails to build with a new GCC: https://github.com/sustrik/libdill/issues/229

**Comment by ikouchiha47** [comment]
travis-ci says gcc-7 , so try with that.

**Comment by barracuda156** [comment]
Closing, since while release is broken, master branch from https://github.com/sustrik/libdill/commit/32d0e8b733416208e0412a56490332772bc5c6e1 builds with gcc14.
